services:
    web-server-1:
        ports:
            - "6001:80"
        volumes:
            - ./server1:/usr/share/nginx/html
        image: nginx
        container_name: web-server-1

    web-server-2:
        ports:
            - "6002:80"
        volumes:
            - ./server2:/usr/share/nginx/html
        image: nginx
        container_name: web-server-2
    
    web-server-3:
        ports:
            - "6003:80"
        volumes:
            - ./server3:/usr/share/nginx/html
        image: nginx
        container_name: web-server-3

